# Generated by Django 5.2.7 on 2025-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends only'), ('ONLY_ME', 'Only me')], default='PUBLIC', max_length=16),
        ),
    ]
