const fs = require('fs')
const path = require('path')

const API_BASE = process.env.API_BASE || process.env.VITE_API_BASE || 'http://localhost:8000'
const WS_BASE = process.env.WS_BASE || process.env.VITE_WS_BASE || 'ws://localhost:8000'

const out = `// generated by scripts/write-env.js\nwindow.__ENV = {\n  API_BASE: '${API_BASE}',\n  WS_BASE: '${WS_BASE}'\n}\n`;

fs.writeFileSync(path.join(__dirname, '..', 'dist', 'env.js'), out)
console.log('Wrote dist/env.js')
