// scripts/write-env.cjs
const fs = require('fs');
const path = require('path');

const isProd = process.env.NODE_ENV === 'production';

// Pull from env first
let API_BASE = process.env.API_BASE || process.env.VITE_API_BASE || '';
let WS_BASE  = process.env.WS_BASE  || process.env.VITE_WS_BASE  || '';

// Sensible defaults per environment
if (!API_BASE) {
  API_BASE = isProd
    ? 'https://cloakpost.onrender.com/api' // ✅ production default
    : 'http://localhost:8000/api';         // dev default (include /api for consistency)
}
if (!WS_BASE) {
  WS_BASE = isProd
    ? 'wss://cloakpost.onrender.com'       // ✅ secure WS in prod
    : 'ws://localhost:8000';               // dev
}

// Normalize/validate
API_BASE = API_BASE.replace(/\/+$/, ''); // no trailing slash
if (!/^https?:\/\//.test(API_BASE)) {
  throw new Error(`API_BASE must be http(s) URL, got: ${API_BASE}`);
}
if (!/^wss?:\/\//.test(WS_BASE)) {
  // auto-upgrade ws scheme to match API_BASE scheme
  const secure = API_BASE.startsWith('https://');
  WS_BASE = (secure ? 'wss://' : 'ws://') + WS_BASE.replace(/^wss?:\/\//, '');
}

const out = `// generated by scripts/write-env.cjs
window.__ENV = {
  API_BASE: '${API_BASE}',
  WS_BASE: '${WS_BASE}'
}
`;

const outPath = path.join(__dirname, '..', 'dist', 'env.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log('Wrote', outPath, 'with:', { API_BASE, WS_BASE });
