# Generated by Django 5.2.7 on 2025-10-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='enc_body',
        ),
    ]
