# Generated by Django 5.2 on 2025-05-07 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='key_salt',
            field=models.BinaryField(default=b"\xf1\xe1vH\x92\x93\x80\xc5\n\xe7\x17\xa0'\x8d\\\xae", max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
